version: '3'
services: 
    db:
        image: postgres:12
        container_name: postgres_db
        restart: always
        ports: 
            - 5433:5432
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - fullstack
        environment: 
            POSTGRES_PASSWORD: Peaceg419
    server:
        build: .
        links: 
            - db
        ports: 
            - 8000:8000
        depends_on: 
            - db
        networks:
            - fullstack
        environment: 
            DATABASE_URL: '${DB_DRIVER}://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?${DB_SSL}' 
            DATABASE_NAME: ${DB_NAME}
            DATA_DIRECTORY: '/${MODULE}/'



volumes:
    postgres_data:                  
    
    
networks:
    fullstack:
        driver: bridge